baseURL = "/"
languageCode = "es-ES"
title = "Blog - TecIguala"
theme = "iti-theme"

[menu]
    [[menu.main]]
    identifier = "programacion"
    name = "Programacion"
    url = "/programacion/"
    weight = 1

    [[menu.main]]
    identifier = "dise침o"
    name = "Dise침o"
    url = "/dise침o/"
    weight = 2

[params]
    description = "Blog de Sistemas y Computaci칩n. TecNM Campus Iguala"
    googleAnalytics = "UA-123-45"